version: '3.8'

services:
  # The Go Backend
  api:
    build: ../backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Docker automatically reads DATABASE_URL from the .env file in this folder
      - DATABASE_URL=${DATABASE_URL}

  # The Next.js Frontend
  web:
    build: ../frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production